version: "3.6"

services:
    updater:
        build: .
        restart: always
        # named volume
        # https://towardsdatascience.com/the-complete-guide-to-docker-volumes-1a06051d2cce
        # Here, the first field is a unique name of the volume on a host machine. 
        # The second part is the path in the container.
        volumes:
            - ./sessions:/updater/sessions

    create_session:
        build: .
        volumes:
            - ./sessions:/updater/sessions
        command: 
            python src/create_session.py