version: "3.6"

services:
    updater:
        build: .
        restart: always
        volumes: 
            - ./sessions:/updater/sessions

    session_creator:
        build: .
        volumes: 
            - ./sessions:/updater/sessions
        command: python misc.py
