version: "3.6"

services:
    updater:
        build: .
        restart: always
        volumes: 
            - ./sessions:./sessions

    session_creator:
        build: .
        volumes: 
            - ./sessions:./sessions
        command: python src/misc.py
