yoda = [
"Life creates it, makes it grow. Its energy surrounds us and binds us.",
"Size matters not. Look at me. Judge me by my size, do you? Hmm? Hmm. ",
"Honor life by living. Killing honors only death: only the dark side.",
"Always two there are, no more, no less. A master and an apprentice.",
"A Jedi uses the force for knowledge and defense, never for attack.",
"And to be joyful only one thing one needs, and that is: be joyful.",
"Defeat the rage that burns in him, and he is your enemy no longer.",
"To live totally fear allows you not, hold you back it always does.",
"You will know (the good from the bad) when you are calm, at peace.",
"All his life has he looked away... to the future, to the horizon.",
"And waited, too, for others to return from journeys of their own.",
"For in fighting the battles, the bloodshed, already lost we have.",
"A Jedi must have the deepest commitment, the most serious mind. ",
"Adventure. Heh! Excitement. Heh! A Jedi craves not these things.",
"Give off light, or darkness, Padawan. Be a candle, or the night.",
"Many of the truths that we cling to depend on our point of view.",
"The more we learn, the more we discover how much we do not know.",
"Understanding is bliss, the cause of misery is misunderstanding.",
"Deeper than your mind is your heart. Love is deeper than logic.",
"Listening to music sometimes, a window opens and happy you are.",
"But only those who live it can know it; no other way there is.",
"Anger, fear, aggression; the dark side of the Force are they.",
"Make the decision, make another. Remake one past, you cannot.",
"To live halfheartedly, this is the most stupid thing in life.",
"Attachment leads to jealously. The shadow of greed, that is.",
"Yet, open to us a path remains. That unknown to the Sith is.",
"And arises in you, then, a totally different kind of being.",
"In love continuously are those people who are called poets.",
"This is what meditation is all about: absence of mentation.",
"A state of beyond, a state of pervasive peace, it denotes.",
"In a vacuum man exists not, like an island man exists not.",
"Rejoice for those around you who transform into the Force.",
"Secret, shall I tell you? Grand Master of Jedi Order am I.",
"What he was doing. Hmph. Adventure. Heh. Excitement. Heh. ",
"Frivolous, speculation is, when patience will reveal all.",
"If informed the senate is, multiply our adversaries will.",
"If routine you count on, disappointed your hopes will be.",
"Doubt in battle, there cannot be. Belief, there must be.",
"Not victory in the Clone Wars, but victory for all time.",
"Train yourself to let go of everything you fear to lose.",
"When you look back, lose your place on the path, you do.",
"Fear is the path to the dark side. Fear leads to anger.",
"In the end, cowards are those who follow the dark side.",
"It connects our pain to all pain, our hurt to all hurt.",
"Powerful you have become, the dark side I sense in you.",
"No longer certain, that one ever does win a war, I am.",
"Desires, memories, imagination, they all come and go.",
"For my ally is the Force, and a powerful ally it is. ",
"In this war, a danger there is, of losing who we are.",
"Of harmony happiness is a shadow, it follows harmony.",
"Only the Dark Lord of the Sith knows of our weakness.",
"Over all words and thoughts it implies transcendence.",
"To answer power with power, the Jedi way this is not.",
"Yoda teaches like drunkards drink, like killers kill.",
"And to people who are more alive, happiness happens.",
"Each moment get out of the past, completely drop it.",
"My own counsel will I keep on who is to be trained. ",
"Then hear what your true heart is seeking, you will.",
"When you look at the dark side, careful you must be.",
"Learn one thing in life you have to - not to cling.",
"Yet between sureness and pride, a small step it is.",
"A great warrior he is, wars do not make one great.",
"As surely as you must guide, you must also be led.",
"A Jedi craves not these things. You are reckless.",
"Difficult to see. Always in motion is the future.",
"Named must your fear be before banish it you can.",
"What you fear to lose, train yourself to release.",
"Finding balance. At rest, be. Of the moment, be.",
"If in anger you answer, then in shame you dwell.",
"If no mistake have you made, yet losing you are.",
"No greater gift there is, than a generous heart.",
"This quality of tremendous acceptance is wisdom.",
"When your path is unsure, better to wait, it is.",
"Your past can ruin your future, if you allow it.",
"Your world you create, too, yourself you create.",
"Easily they flow, quick to join you in a fight.",
"Infinitely more ways there are to reach a goal.",
"Luminous beings are we, not this crude matter. ",
"So great life is, to finish it no way there is.",
"Always more questions than answers, there are.",
"Close your mouth and open your ears, you must.",
"When all choices seem wrong, choose restraint.",
"Anger leads to hate. Hate leads to suffering.",
"Be joyful and grateful - whatsoever you have.",
"For eight hundred years have I trained Jedi. ",
"Smaller in number are we, but larger in mind.",
"The mind is thinking no longer; silent it is.",
"Mind what you have learned. Save you it can.",
"To be Jedi is to face the truth, and choose.",
"To defeat an enemy, you do not have to kill.",
"Impossible to see the light, the future is.",
"Never step in the same river twice can you.",
"Share! Give! and given to you more will be.",
"Silence is not simply calmness or quietude.",
"The art of remaining in the present, learn.",
"Through this path, victory we may yet find.",
"Too long sorrow makes a stone of the heart.",
"Truly how wonderful the mind of a child is.",
"Make a mission great, excitement does not.",
"Twilight is upon me, soon night must fall.",
"A Jedi always sought to avoid a conflict.",
"By chance alone we do not live our lives.",
"Control, control, you must learn control!",
"Let go of fear, and loss cannot harm you.",
"Patience you must have, my young Padawan.",
"Forever gone is the moment that is gone.",
"Happens to every guy sometimes this does",
"Age is how many mistakes you have made.",
"Age more than a count of heartbeats is.",
"Even the blind seed grows to the light.",
"For you to relax is all that is needed.",
"Great warrior. Wars not make one great.",
"Neither the past nor the future exists.",
"Poetic you become when in love you are.",
"Ready are you? What know you of ready? ",
"Truly wonderful the mind of a child is.",
"Always it speaks to us, from our pain.",
"To go beyond the mind, you need trust.",
"Always pass on what you have learned.",
"Mourn them do not. Miss them do not. ",
"Never his mind on where he was. Hmm? ",
"Soon will I rest, yes, forever sleep.",
"This one a long time have I watched. ",
"You will find only what you bring in.",
"Each time he that steps has changed.",
"Tremendously beautiful this life is.",
"With time. With time all are healed.",
"Nothing else, no other requirement.",
"The shadow of greed, attachment is.",
"A decision is yours alone to make.",
"No other way to be happy there is.",
"On many long journeys have I gone.",
"A different game you should play.",
"Death is a natural part of life.",
"The dark side clouds everything.",
"Always in motion is the future.",
"Do not assume anything Obi-Wan.",
"Each time the river hurries on.",
"Out of acceptance comes wisdom.",
"Do or do not. There is no try.",
"Of your ability, sure you are.",
"For the dark side looks back.",
"Learn not to teach, you must.",
"The dark side. Of it be free.",
"Through enjoyment life grows.",
"True to your freedom, remain.",
"Strong am I with the force.",
"Your path you must decide.",
"Hang around, it does not.",
"Try them all, you should.",
"Hate leads to suffering.",
"Rage the true enemy is.",
"Things thoughts become.",
"A way there always is.",
"There it is no longer.",
"Consume you, it will.",
"That is why you fail.",
"In the moment, live.",
"A teacher Yoda is.",
"Attention is food.",
"Earned it I have.",
"Joy is the sutra.",
"Just disconnect.",
"Feel the force!",
"Herenow is joy."
]